package operacionesApp;


/**
* operacionesApp/procesamientoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from operaciones.idl
* sábado 28 de abril de 2018 02:57:31 AM CDT
*/

public interface procesamientoOperations 
{
  String procesarImagenes (String cadena1, String cadena2, String operador);
  void shutdown ();
} // interface procesamientoOperations
