package operacionesApp;


/**
* operacionesApp/procesamiento.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from operaciones.idl
* sábado 28 de abril de 2018 02:57:31 AM CDT
*/

public interface procesamiento extends procesamientoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface procesamiento
