package operacionesApp;


/**
* operacionesApp/procesamientoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from operaciones.idl
* sábado 28 de abril de 2018 02:57:31 AM CDT
*/

public abstract class procesamientoPOA extends org.omg.PortableServer.Servant
 implements operacionesApp.procesamientoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("procesarImagenes", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // operacionesApp/procesamiento/procesarImagenes
       {
         String cadena1 = in.read_string ();
         String cadena2 = in.read_string ();
         String operador = in.read_string ();
         String $result = null;
         $result = this.procesarImagenes (cadena1, cadena2, operador);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // operacionesApp/procesamiento/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:operacionesApp/procesamiento:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public procesamiento _this() 
  {
    return procesamientoHelper.narrow(
    super._this_object());
  }

  public procesamiento _this(org.omg.CORBA.ORB orb) 
  {
    return procesamientoHelper.narrow(
    super._this_object(orb));
  }


} // class procesamientoPOA
