package sumaApp;


/**
* sumaApp/sumaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from suma.idl
* viernes 20 de abril de 2018 04:14:20 PM CDT
*/

public interface sumaOperations 
{
  int sumar (int operador1, int operador2);
  void shutdown ();
} // interface sumaOperations
