package sumaApp;


/**
* sumaApp/sumaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from suma.idl
* sábado 28 de abril de 2018 08:15:10 AM CDT
*/

public interface sumaOperations 
{
  int sumar (int operador1, int operador2);
  void shutdown ();
} // interface sumaOperations
